apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-internal-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}-dpl
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
