apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
{{- if .Values.ingress.annotations }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
{{- end }}    
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range $i, $host := $.Values.ingress.tls }}
  - hosts: 
    {{ toYaml $host.hosts }}
    secretName: {{ $host.secretName }}  
  {{- end }}
{{- end }}     
  rules:
{{- range $i, $rule := $.Values.ingress.rules }}
  - host: {{ $rule.host }}
    http:
      paths:
      {{- range $i, $path := $.Values.ingress.paths }}
      - pathType: {{ $path.pathType }}
        path: "{{ $path.path }}"
      {{- end }}   
        backend:
          service:
          {{- range $i, $backend := $.Values.ingress.backend }}
            name: {{ $backend.service.name }}
            port:
              number: {{ $backend.service.port }}
          {{- end }}              
{{- end }}