apiVersion: v1

kind: Secret
metadata:
  name: {{ .Values.secretMap.name }}
type: Opaque
data:
  db-uri: {{ .Values.secretMap.dburi | b64enc }}
  secret_key: {{ .Values.secretMap.secret_key | b64enc }}