version: "3"

volumes: 
    jenkins_home-portf:

services: 
    jenkins:
        image: jenkins/jenkins:lts
        ports: 
            - 8080:8080
        volumes: 
            - jenkins_home-portf:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker:ro

# run after docker up:
#  $ docker-compose exec -u root jenkins bash
#  $ chmod 666 /var/run/docker.sock            